-- Database initialization script for Task Management Website
-- Creates tables and inserts test data

-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
);

-- Create tasks table
CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Insert test user with BCrypt encoded password for 'Test1234'
-- BCrypt hash generated with strength 10
INSERT OR IGNORE INTO users (username, password, full_name, email) VALUES (
    'test@example.com',
    '$2a$10$zXz7X9K9Qz1Y6o6X1Z7Y6u6K9Qz1Y6o6X1Z7Y6u6K9Qz1Y6o6X1Z7Y6',
    'Test User',
    'test@example.com'
);

-- Note: The actual BCrypt hash will be generated by the application
-- The above is a placeholder format. The real hash will be generated when the application starts.