apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp
  namespace: taskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskapp
  template:
    metadata:
      labels:
        app: taskapp
    spec:
      containers:
        - name: taskapp
          image: taskapp:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: db-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
          readinessProbe:
            httpGet:
              path: /sign-in
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /sign-in
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
